//! End-to-end contracts for the publishable product and private Beads tooling.
//!
//! These tests intentionally cross the Cargo/package/process boundaries.  They
//! are the final proof that the private developer workflow is usable without
//! widening the shipped product surface or mutating the live tracker.

use std::{
    fs,
    path::{Path, PathBuf},
    process::Command,
    time::{SystemTime, UNIX_EPOCH},
};

fn repository_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn temporary_repo(case_id: &str) -> PathBuf {
    let stamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("system clock is after the Unix epoch")
        .as_nanos();
    let root = std::env::temp_dir().join(format!("omnirepo-integration-{case_id}-{stamp}"));
    fs::create_dir_all(root.join(".beads")).expect("create isolated Beads directory");
    root
}

fn package_listing() -> Vec<String> {
    let output = Command::new("cargo")
        .args(["package", "--list", "--allow-dirty", "--locked"])
        .current_dir(repository_root())
        .output()
        .expect("run locked package listing");
    assert!(
        output.status.success(),
        "case=package-list command=cargo package --list --allow-dirty --locked\nstdout={}\nstderr={}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8(output.stdout)
        .expect("package listing is UTF-8")
        .lines()
        .map(str::to_owned)
        .collect()
}

#[test]
fn product_package_contains_runtime_only_files() {
    let listing = package_listing();
    let allowed = [
        "CHANGELOG.md",
        "CONSTITUTION.md",
        "Cargo.lock",
        "Cargo.toml",
        "LICENSE",
        "README.md",
        "src/main.rs",
        "src/configuration/mod.rs",
        "src/configuration/discovery.rs",
        "src/configuration/yaml_subset.rs",
        "src/lifecycle/mod.rs",
        "src/lifecycle/event.rs",
        "src/lifecycle/invocation.rs",
        "src/lifecycle/journal.rs",
        "src/lifecycle/replay.rs",
        "src/lifecycle/replace.rs",
        "src/lifecycle/transaction_evidence.rs",
        "src/lifecycle/run_record.rs",
        "src/managed_content/mod.rs",
        "src/managed_content/compare.rs",
        "src/managed_content/transaction.rs",
        "src/platform/mod.rs",
        "src/platform/authority/mod.rs",
        "src/repository/mod.rs",
        "src/repository/capture.rs",
        "src/repository/policy.rs",
        "src/repository/manifest.rs",
        "src/repository/policy_loader.rs",
        "src/repository/revalidate.rs",
        "src/repository/state.rs",
        "src/source/mod.rs",
        "src/source/acquisition.rs",
        "src/source/publish.rs",
        "src/source/snapshot.rs",
        // Cargo injects these two metadata files while packaging. They are
        // generated by Cargo and cannot be excluded from `cargo package`.
        ".cargo_vcs_info.json",
        "Cargo.toml.orig",
    ];
    let forbidden = [
        ".beads/",
        ".cargo/",
        ".github/",
        ".codex/",
        ".claude/",
        "canon/",
        "docs/",
        "scripts/",
        "tests/",
        "tools/",
        ".gitignore",
        ".pre-commit-config.yaml",
        "AGENTS.md",
        "CLAUDE.md",
        "cog.toml",
    ];
    let unexpected = listing
        .iter()
        .filter(|entry| !allowed.contains(&entry.as_str()))
        .cloned()
        .collect::<Vec<_>>();
    let package_message = format!(
        "case=package-runtime-allowlist command=cargo package --list --allow-dirty --locked\nunexpected entries={unexpected:?}\nreplay=rtk cargo package --list --allow-dirty --locked"
    );
    assert!(unexpected.is_empty(), "{package_message}");
    for path in [
        "src/configuration/unit_tests.rs",
        "src/managed_content/transaction_tests.rs",
        "src/source/snapshot_tests.rs",
        "src/repository/policy_tests.rs",
        "src/repository/state_tests.rs",
    ] {
        assert!(
            !listing.iter().any(|entry| entry == path),
            "case=package-test-only-exclusion path={path} command=cargo package --list --allow-dirty --locked\nartifact=package-list\nreplay=rtk cargo package --list --allow-dirty --locked"
        );
    }
    for path in forbidden {
        let exclusion_message = format!(
            "case=package-exclusion path={path} command=cargo package --list --allow-dirty --locked\nartifact=package-list\nreplay=rtk cargo package --list --allow-dirty --locked"
        );
        assert!(
            !listing
                .iter()
                .any(|entry| entry == path || entry.starts_with(path)),
            "{exclusion_message}"
        );
    }
}

#[test]
fn validator_is_read_only_and_independent_of_br() {
    let root = temporary_repo("validator-read-only");
    let tracked = root.join(".beads/issues.jsonl");
    let original = b"{\"id\":\"ordinary\",\"status\":\"open\",\"labels\":[]}\n";
    fs::write(&tracked, original).expect("write isolated tracker export");
    let manifest = repository_root().join("tools/omnirepo-dev/Cargo.toml");
    let output = Command::new("cargo")
        .args(["run", "--quiet", "--locked", "--manifest-path"])
        .arg(&manifest)
        .args(["--", "validate-decisions", "--json"])
        .current_dir(&root)
        .env("BEADS_JSONL", &tracked)
        .output()
        .expect("run Rust validator without br");
    let validator_message = format!(
        "case=validator-read-only seed=3101 command=omnirepo-dev validate-decisions --json\nstdout={}\nstderr={}\nartifact={}\nreplay=rtk cargo test --locked --test workspace_tooling_integration validator_is_read_only_and_independent_of_br -- --nocapture",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
        tracked.display()
    );
    assert!(output.status.success(), "{validator_message}");
    assert!(
        output.stderr.is_empty(),
        "JSON diagnostics must stay on stdout"
    );
    assert_eq!(fs::read(&tracked).expect("read tracker export"), original);
    fs::remove_dir_all(root).expect("remove isolated validator fixture");
}

#[test]
fn developer_dispatcher_has_stable_failure_and_replay_projection() {
    let manifest = repository_root().join("tools/omnirepo-dev/Cargo.toml");
    let output = Command::new("cargo")
        .args(["run", "--quiet", "--locked", "--manifest-path"])
        .arg(manifest)
        .args(["--", "unsupported-integration-command"])
        .output()
        .expect("run developer dispatcher");
    assert_eq!(output.status.code(), Some(2));
    let stderr = String::from_utf8(output.stderr).expect("diagnostic is UTF-8");
    assert!(stderr.contains("unsupported developer command"));
    assert!(stderr.ends_with('\n'));
}

#[allow(dead_code)]
fn _assert_fixture_is_inside_temp_root(path: &Path) {
    assert!(path.starts_with(std::env::temp_dir()));
}
